### ISSUE TITLE
[MYHEALING] 가이드 세부사항 수정

### ISSUE THREAD

**Issue by tigowler** [Likelion-at-SMWU-10th/MYHEALING-Server#17]
## 📌Feature Issue
- 프론트와 상의 후 model에서 수정해야 할 부분 우선 수정하기

## 📚 To-do
- [x] 가이드 이미지 여러 개 저장되도록 하기
- [x] 첫번째 사진이 무조건 thumbnail로 지정되게 하기
- [x] 지출 금액은 CharField가 아닌 Integer로 변경
- [x] Guide 저장 시 ManytoManyField tag 저장
