### ISSUE TITLE
[MYHEALING] 가이드 및 추억 남기기 2차 수정

### ISSUE THREAD

**Issue by tigowler** [Likelion-at-SMWU-10th/MYHEALING-Server#31]
## 📌Feature Issue
- 배포 이후 수정할 내용이 생겨 2차 수정 계획

## 📚 To-do
- [x] [POST] 추억 남기기 → scope 필드 삭제, address 추가
- [x] [GET] 페이지 당 목록 개수 10개로 수정
- [x] [GET] 가이드 상세페이지 → 현재 로그인한 사용자의 해당 가이드 찜한 상태 여부 Response에 추가하기
- [x] 과거 DB에 남아있는 '숙대 탐방' 글들 지우기
- [ ] ppk key 공유하여 배포 다시하기
